import {
  Edit,
  Eraser,
  FileText,
  Hash,
  ImageIcon,
  Scissors,
  Sparkles,
} from "lucide-react";
import type { FormConfig } from "./AiToolForm";

export const getArticleFormConfig = (dict: any): FormConfig => ({
  icon: Sparkles,
  title: dict.ai.formConfigs.article.title,
  iconColor: "text-[#4A7AFF]",
  inputLabel: dict.ai.formConfigs.article.inputLabel,
  inputPlaceholder: dict.ai.formConfigs.article.inputPlaceholder,
  optionsLabel: dict.ai.formConfigs.article.optionsLabel,
  options: dict.ai.formConfigs.article.options,
  selectedColor: "text-blue-700",
  selectedBgColor: "bg-blue-50",
  buttonIcon: Edit,
  buttonText: dict.ai.formConfigs.article.buttonText,
  buttonGradientFrom: "from-[#226BFF]",
  buttonGradientTo: "to-[#65ADFF]",
});

export const getBlogTitlesFormConfig = (dict: any): FormConfig => ({
  icon: Sparkles,
  title: dict.ai.formConfigs.blogTitles.title,
  iconColor: "text-[#8E37EB]",
  inputLabel: dict.ai.formConfigs.blogTitles.inputLabel,
  inputPlaceholder: dict.ai.formConfigs.blogTitles.inputPlaceholder,
  optionsLabel: dict.ai.formConfigs.blogTitles.optionsLabel,
  options: dict.ai.formConfigs.blogTitles.options,
  selectedColor: "text-purple-700",
  selectedBgColor: "bg-purple-50",
  buttonIcon: Hash,
  buttonText: dict.ai.formConfigs.blogTitles.buttonText,
  buttonGradientFrom: "from-[#C341F6]",
  buttonGradientTo: "to-[#8E37EB]",
});

export const getImageGenerationFormConfig = (dict: any): FormConfig => ({
  icon: Sparkles,
  title: dict.ai.formConfigs.imageGeneration.title,
  iconColor: "text-[#00AD25]",
  inputLabel: dict.ai.formConfigs.imageGeneration.inputLabel,
  inputPlaceholder: dict.ai.formConfigs.imageGeneration.inputPlaceholder,
  inputType: "textarea",
  inputRows: 4,
  optionsLabel: dict.ai.formConfigs.imageGeneration.optionsLabel,
  options: dict.ai.formConfigs.imageGeneration.options,
  selectedColor: "text-green-700",
  selectedBgColor: "bg-green-50",
  buttonIcon: ImageIcon,
  buttonText: dict.ai.formConfigs.imageGeneration.buttonText,
  buttonGradientFrom: "from-[#00AD25]",
  buttonGradientTo: "to-[#04FF50]",
});

export const getBackgroundRemovalFormConfig = (dict: any): FormConfig => ({
  icon: Sparkles,
  title: dict.ai.formConfigs.backgroundRemoval.title,
  iconColor: "text-[#FF6B35]",
  inputLabel: dict.ai.formConfigs.backgroundRemoval.inputLabel,
  inputPlaceholder: dict.ai.formConfigs.backgroundRemoval.inputPlaceholder,
  inputType: "file",
  inputRows: 1,
  optionsLabel: "",
  options: [],
  selectedColor: "text-red-700",
  selectedBgColor: "bg-red-50",
  buttonIcon: Eraser,
  buttonText: dict.ai.formConfigs.backgroundRemoval.buttonText,
  buttonGradientFrom: "from-[#FF6B35]",
  buttonGradientTo: "to-[#FF0000]",
});

export const getObjectRemovalFormConfig = (dict: any): FormConfig => ({
  icon: Sparkles,
  title: dict.ai.formConfigs.objectRemoval.title,
  iconColor: "text-[#4A7AFF]",
  inputLabel: dict.ai.formConfigs.objectRemoval.inputLabel,
  inputPlaceholder: dict.ai.formConfigs.objectRemoval.inputPlaceholder,
  inputType: "textarea",
  inputRows: 4,
  optionsLabel: "",
  options: [],
  selectedColor: "text-blue-700",
  selectedBgColor: "bg-blue-50",
  buttonIcon: Scissors,
  buttonText: dict.ai.formConfigs.objectRemoval.buttonText,
  buttonGradientFrom: "from-[#4A7AFF]",
  buttonGradientTo: "to-[#8E37EB]",
});

export const getResumeReviewFormConfig = (dict: any): FormConfig => ({
  icon: Sparkles,
  title: dict.ai.formConfigs.resumeReview.title,
  iconColor: "text-[#00D4AA]",
  inputLabel: dict.ai.formConfigs.resumeReview.inputLabel,
  inputPlaceholder: dict.ai.formConfigs.resumeReview.inputPlaceholder,
  inputType: "file",
  inputRows: 1,
  optionsLabel: "",
  options: [],
  selectedColor: "text-green-700",
  selectedBgColor: "bg-green-50",
  buttonIcon: FileText,
  buttonText: dict.ai.formConfigs.resumeReview.buttonText,
  buttonGradientFrom: "from-[#00D4AA]",
  buttonGradientTo: "to-[#00B4D8]",
});
