import {
  Edit,
  Eraser,
  FileText,
  Hash,
  ImageIcon,
  Scissors,
  Sparkles,
} from "lucide-react";
import type { FormConfig } from "./AiToolForm";

export const articleFormConfig: FormConfig = {
  icon: Sparkles,
  title: "Article Configuration",
  iconColor: "text-[#4A7AFF]",
  inputLabel: "Article Topic",
  inputPlaceholder: "The future of artificial intelligence is...",
  optionsLabel: "Article Length",
  options: [
    { text: "Short（500-800 words）", value: 800 },
    { text: "Medium（800-1200 words） ", value: 1200 },
    { text: "Long（1200+ words）", value: 1600 },
  ],
  selectedColor: "text-blue-700",
  selectedBgColor: "bg-blue-50",
  buttonIcon: Edit,
  buttonText: "Generate article",
  buttonGradientFrom: "from-[#226BFF]",
  buttonGradientTo: "to-[#65ADFF]",
};

export const blogTitlesFormConfig: FormConfig = {
  icon: Sparkles,
  title: "Blog Title Generator",
  iconColor: "text-[#8E37EB]",
  inputLabel: "Blog Topic",
  inputPlaceholder: "The future of artificial intelligence is...",
  optionsLabel: "Blog Category",
  options: [
    "General",
    "Technology",
    "Business",
    "Health",
    "Lifestyle",
    "Education",
    "Travel",
    "Food",
  ],
  selectedColor: "text-purple-700",
  selectedBgColor: "bg-purple-50",
  buttonIcon: Hash,
  buttonText: "Generate title",
  buttonGradientFrom: "from-[#C341F6]",
  buttonGradientTo: "to-[#8E37EB]",
};

export const imageGenerationFormConfig: FormConfig = {
  icon: Sparkles,
  title: "AI Image Generator",
  iconColor: "text-[#00AD25]",
  inputLabel: "Describe Your Image",
  inputPlaceholder: "Describe what you want to see in the image..",
  inputType: "textarea",
  inputRows: 4,
  optionsLabel: "Style",
  options: [
    "Realistic",
    "Ghibli style",
    "Anime style",
    "Cartoon style",
    "Fantasy style",
    "Realistic style",
    "3D style",
    "Portrait style",
  ],
  selectedColor: "text-green-700",
  selectedBgColor: "bg-green-50",
  buttonIcon: ImageIcon,
  buttonText: "Generate Image",
  buttonGradientFrom: "from-[#00AD25]",
  buttonGradientTo: "to-[#04FF50]",
};

export const backgroundRemovalFormConfig: FormConfig = {
  icon: Sparkles,
  title: "Background Removal",
  iconColor: "text-[#FF6B35]",
  inputLabel: "Upload image",
  inputPlaceholder: "No file chosen",
  inputType: "file",
  inputRows: 1,
  optionsLabel: "",
  options: [],
  selectedColor: "text-red-700",
  selectedBgColor: "bg-red-50",
  buttonIcon: Eraser,
  buttonText: "Remove background",
  buttonGradientFrom: "from-[#FF6B35]",
  buttonGradientTo: "to-[#FF0000]",
};

export const objectRemovalFormConfig: FormConfig = {
  icon: Sparkles,
  title: "Object Removal",
  iconColor: "text-[#4A7AFF]",
  inputLabel: "Describe object to remove",
  inputPlaceholder: "e.g., car in background, tree from the image",
  inputType: "textarea",
  inputRows: 4,
  optionsLabel: "",
  options: [],
  selectedColor: "text-blue-700",
  selectedBgColor: "bg-blue-50",
  buttonIcon: Scissors,
  buttonText: "Remove object",
  buttonGradientFrom: "from-[#4A7AFF]",
  buttonGradientTo: "to-[#8E37EB]",
};

export const resumeReviewFormConfig: FormConfig = {
  icon: Sparkles,
  title: "Resume Review",
  iconColor: "text-[#00D4AA]",
  inputLabel: "Upload Resume",
  inputPlaceholder: "No file chosen",
  inputType: "file",
  inputRows: 1,
  optionsLabel: "",
  options: [],
  selectedColor: "text-green-700",
  selectedBgColor: "bg-green-50",
  buttonIcon: FileText,
  buttonText: "Review Resume",
  buttonGradientFrom: "from-[#00D4AA]",
  buttonGradientTo: "to-[#00B4D8]",
};
