import {
  Edit,
  Eraser,
  FileText,
  Hash,
  ImageIcon,
  Scissors,
  Sparkles,
} from "lucide-react";
import type { FormConfig } from "./AiToolForm";

export const articleFormConfig: FormConfig = {
  icon: Sparkles,
  title: "文章生成器",
  iconColor: "text-[#4A7AFF]",
  inputLabel: "文章主题",
  inputPlaceholder: "人工智能的未来发展...",
  optionsLabel: "文章长度",
  options: [
    { text: "短篇（500-800字）", value: 800 },
    { text: "中篇（800-1200字）", value: 1200 },
    { text: "长篇（1200+字）", value: 1600 },
  ],
  selectedColor: "text-blue-700",
  selectedBgColor: "bg-blue-50",
  buttonIcon: Edit,
  buttonText: "生成文章",
  buttonGradientFrom: "from-[#226BFF]",
  buttonGradientTo: "to-[#65ADFF]",
};

export const blogTitlesFormConfig: FormConfig = {
  icon: Sparkles,
  title: "博客标题生成器",
  iconColor: "text-[#8E37EB]",
  inputLabel: "博客主题",
  inputPlaceholder: "人工智能的未来发展...",
  optionsLabel: "博客分类",
  options: ["综合", "科技", "商业", "健康", "生活", "教育", "旅游", "美食"],
  selectedColor: "text-purple-700",
  selectedBgColor: "bg-purple-50",
  buttonIcon: Hash,
  buttonText: "生成标题",
  buttonGradientFrom: "from-[#C341F6]",
  buttonGradientTo: "to-[#8E37EB]",
};

export const imageGenerationFormConfig: FormConfig = {
  icon: Sparkles,
  title: "AI图像生成器",
  iconColor: "text-[#00AD25]",
  inputLabel: "图像描述",
  inputPlaceholder: "描述你想要生成的图像内容...",
  inputType: "textarea",
  inputRows: 4,
  optionsLabel: "风格",
  options: [
    "写实风格",
    "吉卜力风格",
    "动漫风格",
    "卡通风格",
    "奇幻风格",
    "超写实风格",
    "3D风格",
    "肖像风格",
  ],
  selectedColor: "text-green-700",
  selectedBgColor: "bg-green-50",
  buttonIcon: ImageIcon,
  buttonText: "生成图像",
  buttonGradientFrom: "from-[#00AD25]",
  buttonGradientTo: "to-[#04FF50]",
};

export const backgroundRemovalFormConfig: FormConfig = {
  icon: Sparkles,
  title: "背景移除",
  iconColor: "text-[#FF6B35]",
  inputLabel: "上传图像",
  inputPlaceholder: "未选择文件",
  inputType: "file",
  inputRows: 1,
  optionsLabel: "",
  options: [],
  selectedColor: "text-red-700",
  selectedBgColor: "bg-red-50",
  buttonIcon: Eraser,
  buttonText: "移除背景",
  buttonGradientFrom: "from-[#FF6B35]",
  buttonGradientTo: "to-[#FF0000]",
};

export const objectRemovalFormConfig: FormConfig = {
  icon: Sparkles,
  title: "对象移除",
  iconColor: "text-[#4A7AFF]",
  inputLabel: "描述要移除的对象",
  inputPlaceholder: "例如：背景中的汽车，图像中的树木",
  inputType: "textarea",
  inputRows: 4,
  optionsLabel: "",
  options: [],
  selectedColor: "text-blue-700",
  selectedBgColor: "bg-blue-50",
  buttonIcon: Scissors,
  buttonText: "移除对象",
  buttonGradientFrom: "from-[#4A7AFF]",
  buttonGradientTo: "to-[#8E37EB]",
};

export const resumeReviewFormConfig: FormConfig = {
  icon: Sparkles,
  title: "简历审查",
  iconColor: "text-[#00D4AA]",
  inputLabel: "上传简历",
  inputPlaceholder: "未选择文件",
  inputType: "file",
  inputRows: 1,
  optionsLabel: "",
  options: [],
  selectedColor: "text-green-700",
  selectedBgColor: "bg-green-50",
  buttonIcon: FileText,
  buttonText: "审查简历",
  buttonGradientFrom: "from-[#00D4AA]",
  buttonGradientTo: "to-[#00B4D8]",
};
